### ISSUE TITLE
XCODE14 Clover r5158++ compil error due to use of undeclared identifier 'TIMEOUTFP' in ~/CloverBootloader/Library/OsxBdsPlatformLib/BdsPlatform.c

### ISSUE THREAD

**Issue by matxpa** [CloverHackyColor/CloverBootloader#691]
@SergeySlice

Hi Slice

"./buildme XCODE14" (r5159++ with different commits since 20240511, ... F.Y.I : local CloverBootloader repo is uptodate)

Compil error due to use of undeclared identifier 'TIMEOUTFP' in ~/CloverBootloader/Library/OsxBdsPlatformLib/BdsPlatform.c

8) build Clover (with XCode) --> XCODE14 (Monterey constraint (XCODE 14.2 max))

...
Running edk2 build for CloverX64 using the command:
build --cmd-len=50000 -D NO_GRUB_DRIVERS_EMBEDDED --conf=/~/CloverBootloader/Conf -D USE_LOW_EBDA -p Clover.dsc  -a X64 -b RELEASE -t XCODE14 -n 5 

Build environment: macOS-12.7.5-x86_64-i386-64bit
Build start time: 19:22:25, May.13 2024

WORKSPACE        = /~/CloverBootloader
EDK_TOOLS_PATH   = /~/CloverBootloader/BaseTools
CONF_PATH        = /~/CloverBootloader/Conf
PYTHON_COMMAND   = python3

Processing meta-data .
Architecture(s)  = X64
Build target     = RELEASE
Toolchain        = XCODE14
...
[SLINK] CustomizedDisplayLib
[CC] AutoGen
make: Nothing to be done for `tbuild'.
/~/CloverBootloader/Library/OsxBdsPlatformLib/BdsPlatform.c:1295:35: error: use of undeclared identifier 'TIMEOUTFP'
  PlatformBdsDiagnostics (IGNORE, TIMEOUTFP, BaseMemoryTest); //Slice - I want silent boot but with Memory test
                                  ^
/~/CloverBootloader/Library/OsxBdsPlatformLib/BdsPlatform.c:1307:13: error: use of undeclared identifier 'TIMEOUTFP'
  Timeout = TIMEOUTFP;
            ^
2 errors generated.
make: *** [/~/CloverBootloader/Build/Clover/RELEASE_XCODE14/X64/Library/OsxBdsPlatformLib/PlatformBds/OUTPUT/BdsPlatform.obj] Error 1

build.py...
 : error 7000: Failed to execute command
	make tbuild [/~/CloverBootloader/Build/Clover/RELEASE_XCODE14/X64/Library/OsxBdsPlatformLib/PlatformBds]

build.py...
 : error F002: Failed to build module
	/~/CloverBootloader/Library/OsxBdsPlatformLib/PlatformBds.inf [X64, XCODE14, RELEASE]

- Failed -
Build end time: 19:22:39, May.13 2024
Build total time: 00:00:14

Regards

**Comment by SergeySlice** [comment]
This is macros defined in PlatformBds.inf
~~~~
[BuildOptions]
# TIMEOUTFP=0 -- silent boot
  XCODE:*_*_*_CC_FLAGS = -DTIMEOUTFP=0
  GCC:*_*_*_CC_FLAGS = -DTIMEOUTFP=0
  MSFT:*_*_*_CC_FLAGS = -DTIMEOUTFP=3

~~~~

**Comment by chris1111** [comment]
No issue building from  Xcode Version 15.4 beta (15F5021i)
macOS Sonoma 14.5 (23F79)

![Screenshot 2024-05-13 at 8 27 54 PM](https://github.com/CloverHackyColor/CloverBootloader/assets/6248794/7ebbc9b5-4ef4-4fdb-88e6-fcdb21e4054a)

![Screenshot 2024-05-13 at 8 27 19 PM](https://github.com/CloverHackyColor/CloverBootloader/assets/6248794/c3c53a24-cc29-4ea1-8809-8255dfe95f09)

**Comment by matxpa** [comment]
Hi

Are you realy sur what I see, on your first screenshot,

is 

Running edk2 build for Clover64 using the command:

build --cmd-len=50000 -D NO_GRUB_DRIVERS --conf=/Users/chris/src/CloverBootloader/Conf -D USE_LOW_EBDA -p Clover.dsc -a X64 -b RELEASE -t XCODE8 -n 5”

 

XCODE8 is NOT XCODE15

 

Regards

 

De : chris1111 ***@***.***>
Répondre à : CloverHackyColor/CloverBootloader ***@***.***>
Date : mardi 14 mai 2024 à 02:31
À : CloverHackyColor/CloverBootloader ***@***.***>
Cc : Jean-Michel Meunier ***@***.***>, Author ***@***.***>
Objet : Re: [CloverHackyColor/CloverBootloader] XCODE14 Clover r5158++ compil error due to use of undeclared identifier 'TIMEOUTFP' in ~/CloverBootloader/Library/OsxBdsPlatformLib/BdsPlatform.c (Issue #691)

 

No issue building from Xcode Version 15.4 beta (15F5021i)
macOS Sonoma 14.5 (23F79)

Screenshot.2024-05-13.at.8.27.54.PM.png (view on web)

Screenshot.2024-05-13.at.8.27.19.PM.png (view on web)

**Comment by chris1111** [comment]
My point is not about a specific version of Xcode but rather to show you that compiling Clover with Xcode has no problem
See default toolchain from ebuild.sh

![Screenshot 0](https://github.com/CloverHackyColor/CloverBootloader/assets/6248794/5a7ac718-3be2-47b0-9b26-39caf1e56d3f)

I don't use buildme,I never use it I use basic commands in macOS Sonoma 14 the latest and I will show you that it also works in Monterey 12 with Xcode 14.3.1

![Screen Shot 1](https://github.com/CloverHackyColor/CloverBootloader/assets/6248794/0f300f06-730a-4778-bd25-4d97129e4494)

![Screen Shot 2](https://github.com/CloverHackyColor/CloverBootloader/assets/6248794/f2c9248c-dd00-46c1-b330-b598479f6c33)

![Screen Shot 3](https://github.com/CloverHackyColor/CloverBootloader/assets/6248794/b754f2ac-08c1-44d4-a98c-41b5c683467a)

![Screen Shot 4](https://github.com/CloverHackyColor/CloverBootloader/assets/6248794/b16c1d2a-8844-4abd-b80c-88eecdb733ec)

![Screen Shot 5](https://github.com/CloverHackyColor/CloverBootloader/assets/6248794/4e722800-1f5a-4c78-89ef-df1da95fd955)





So it work from Monterey to Sonoma
